name: Build and deploy Java JAR app to Digital Ocean

# Quand executer la tache de déploiement
on:
  push:
    branches:
      - deploy-test

# Les listes des taches
jobs:
  deploy:
    runs-on: ubuntu-latest
    
  # Les etapes de la tâche  
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up java
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Deploy to Droplet
      uses: applyboy/ssh-action@master
      with:
        host: 157.245.45.203
        username: root
        password: e8]2Qq7wV;>=a7D
