name: Build and deploy Java JAR app to Digital Ocean

# Quand executer la tache de déploiement
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["deploy-test"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Les listes des taches
jobs:
  deploy:
    name: Deploy to Ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: adopt

    - name: Build with Gradle
      run: chmod +x ./gradlew ; ./gradlew build

    - name: Deploy to Droplet
      uses: appleboy/scp-action@master
      with:
        host: 157.245.45.203
        username: root
        password: e8]2Qq7wV;>=a7D
        source: "build/libs/tp_filmotheque-0.0.1-SNAPSHOT.jar"
        target: /home/

    - name: Run to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: 157.245.45.203
        username: root
        password: e8]2Qq7wV;>=a7D
        script: systemctl start spring_server
