name: Build and deploy Java JAR app to Digital Ocean

# Quand executer la tache de déploiement
on:
  # Run to deploy-test
  push:
    branches: ["deploy-test"]

  workflow_dispatch:

# Les listes des taches
jobs:
  deploy:
    name: Deploy to Ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: adopt

    - name: Build with Gradle
      run: chmod +x ./gradlew ; ./gradlew build

    - name: Deploy to Droplet
      uses: appleboy/scp-action@master
      with:
        host: 157.245.45.203
        username: root
        password: e8]2Qq7wV;>=a7D
        source: "build/libs/tp_filmotheque-0.0.1-SNAPSHOT.jar"
        target: /home/

    - name: Run to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: 157.245.45.203
        username: root
        password: e8]2Qq7wV;>=a7D
        script: java -jar /home/tp_filmotheque-0.0.1-SNAPSHOT.jar
